### PR TITLE
added support of xml

### LINKED ISSUE #31: Add XML support
Similar to Json

### PR DESCRIPTION
**Pull request by Szer**
Closes #31

### CODE REVIEW

**Comment by bessgeor** [comment]
Seems like you have forgotten to test against XML input (i.e. request containing an xml body)

**Comment by Szer** [comment]
@bessgeor hmmm, that's right :D

**Comment by Szer** [comment]
@bessgeor added xml test with body

**Comment by bessgeor** [comment]
LGTM

**Pull request merged**
